version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "15:00"
      timezone: "Europe/Helsinki"
    assignees: ["jvnipers"]
    commit-message:
      prefix: "github-actions"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "15:00"
      timezone: "Europe/Helsinki"
    assignees: ["jvnipers"]
    commit-message:
      prefix: "npm"
    groups: 
      "All Deps": 
        applies-to: "version-updates"
        patterns: ["*"]
